TALLER API Y POWER BI

1.Iniciaremos instalando  e importando requests, lo cual nos sirve para que python pueda conectarse con pag web

2.(.get) nos entrega los datos que están en la URL que pongamos seguidamente

3.(status_code) como su nombre lo dice, este nos ayuda a verificar si la conexión tuvo éxito
o si hay errores, si es exitosa su respuesta debe ser igual a 200.

4.Transformamos el formato con resp.jason()

5.Importamos pandas y creamos nuestra variable para que almacene nuestro nuevo DataFrame.

6.Reavisamos nuestro DF con los códigos que ya conocemos para obtener conocimiento sobre nuestro DataSet.

7.Realizamos la respectiva limpieza para eliminar nulos y/o posible duplicidad.

8.Exportación a CSV

In [9]:
!pip install requests

Requirement already satisfied: requests in c:\users\lolit\appdata\local\programs\python\python314\lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lolit\appdata\local\programs\python\python314\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lolit\appdata\local\programs\python\python314\lib\site-packages (from requests) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\lolit\appdata\local\programs\python\python314\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\lolit\appdata\local\programs\python\python314\lib\site-packages (from requests) (2026.4.22)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import requests

In [11]:
resp = requests.get("https://api-colombia.com/api/v1/NaturalArea")

In [12]:
resp.status_code

200

In [13]:
resp.json()

[{'id': 1,
  'areaGroupId': 6,
  'categoryNaturalAreaId': 7,
  'name': 'Cueva de los Guácharos',
  'departmentId': 18,
  'daneCode': 41,
  'landArea': 4873.0575943204,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 2,
  'areaGroupId': 6,
  'categoryNaturalAreaId': 7,
  'name': 'Cueva de los Guácharos',
  'departmentId': 18,
  'daneCode': 41,
  'landArea': 15.759621378006,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 3,
  'areaGroupId': 6,
  'categoryNaturalAreaId': 7,
  'name': 'Cueva de los Guácharos',
  'departmentId': 9,
  'daneCode': 18,
  'landArea': 5.6247458407797,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 4,
  'areaGroupId': 6,
  'categoryNaturalAreaId': 7,
  'name': 'Cueva de los Guácharos',
  'departmentId': 11,
  'daneCode': 19,
  'landArea': 1099.0191451941,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 5,
  'areaGroupId': 6,
  'categoryNaturalAreaId': 7,
  'name': 'Cueva de los Guácharos',
  'departmentId': 9,
  'daneCode': 18,
  'landArea': 1141.4589764049,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 6,
  'areaGroupId': 6,
  'categoryNaturalAreaId': 7,
  'name': 'Cueva de los Guácharos',
  'departmentId': 18,
  'daneCode': 41,
  'landArea': 4888.8172140187,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 7,
  'areaGroupId': 6,
  'categoryNaturalAreaId': 7,
  'name': 'Cueva de los Guácharos',
  'departmentId': 11,
  'daneCode': 19,
  'landArea': 1099.0191451941,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 8,
  'areaGroupId': 6,
  'categoryNaturalAreaId': 7,
  'name': 'Cueva de los Guácharos',
  'departmentId': 9,
  'daneCode': 18,
  'landArea': 1147.0837223144,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 9,
  'areaGroupId': 8,
  'categoryNaturalAreaId': 2,
  'name': 'Nukak',
  'departmentId': 17,
  'daneCode': 95,
  'landArea': 4714.5397670615,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 10,
  'areaGroupId': 8,
  'categoryNaturalAreaId': 2,
  'name': 'Nukak',
  'departmentId': 17,
  'daneCode': 95,
  'landArea': 645756.28359524,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 11,
  'areaGroupId': 8,
  'categoryNaturalAreaId': 2,
  'name': 'Nukak',
  'departmentId': 32,
  'daneCode': 97,
  'landArea': 141.76105577393,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 12,
  'areaGroupId': 8,
  'categoryNaturalAreaId': 2,
  'name': 'Nukak',
  'departmentId': 17,
  'daneCode': 95,
  'landArea': 215874.31697955,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 13,
  'areaGroupId': 8,
  'categoryNaturalAreaId': 2,
  'name': 'Nukak',
  'departmentId': 32,
  'daneCode': 97,
  'landArea': 8403.6065516163,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 14,
  'areaGroupId': 8,
  'categoryNaturalAreaId': 2,
  'name': 'Nukak',
  'departmentId': 32,
  'daneCode': 97,
  'landArea': 8545.3676073902,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 15,
  'areaGroupId': 8,
  'categoryNaturalAreaId': 2,
  'name': 'Nukak',
  'departmentId': 17,
  'daneCode': 95,
  'landArea': 866345.14034256,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 16,
  'areaGroupId': 9,
  'categoryNaturalAreaId': 9,
  'name': 'Dinaboy',
  'departmentId': 31,
  'daneCode': 76,
  'landArea': 212.24696857155,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 17,
  'areaGroupId': 9,
  'categoryNaturalAreaId': 9,
  'name': 'Dinaboy',
  'departmentId': 31,
  'daneCode': 76,
  'landArea': 212.24696857155,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 18,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 30,
  'daneCode': 73,
  'landArea': 220.05089620604,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 19,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 8,
  'daneCode': 17,
  'landArea': 9086.6811470079,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 20,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 30,
  'daneCode': 73,
  'landArea': 1639.1206272116,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 21,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 30,
  'daneCode': 73,
  'landArea': 8918.3879837344,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 22,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 26,
  'daneCode': 66,
  'landArea': 9376.1269795061,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 23,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 30,
  'daneCode': 73,
  'landArea': 1530.6299592023,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 24,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 30,
  'daneCode': 73,
  'landArea': 3987.6416181338,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 25,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 30,
  'daneCode': 73,
  'landArea': 6786.5309794753,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 26,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 25,
  'daneCode': 63,
  'landArea': 2350.2669482272,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 27,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 30,
  'daneCode': 73,
  'landArea': 5552.9733996514,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 28,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 26,
  'daneCode': 66,
  'landArea': 11925.080677239,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 29,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 30,
  'daneCode': 73,
  'landArea': 28635.335466957,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 30,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 26,
  'daneCode': 66,
  'landArea': 21301.207656751,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 31,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 25,
  'daneCode': 63,
  'landArea': 2350.2669482272,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 32,
  'areaGroupId': 11,
  'categoryNaturalAreaId': 7,
  'name': 'Los Nevados',
  'departmentId': 8,
  'daneCode': 17,
  'landArea': 9086.6811470079,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 33,
  'areaGroupId': 12,
  'categoryNaturalAreaId': 9,
  'name': 'Las Bromelias',
  'departmentId': 11,
  'daneCode': 19,
  'landArea': 9.2128203076564,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 34,
  'areaGroupId': 12,
  'categoryNaturalAreaId': 9,
  'name': 'Las Bromelias',
  'departmentId': 11,
  'daneCode': 19,
  'landArea': 9.0590150170655,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 35,
  'areaGroupId': 12,
  'categoryNaturalAreaId': 9,
  'name': 'Las Bromelias',
  'departmentId': 11,
  'daneCode': 19,
  'landArea': 0.15380537194414,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 36,
  'areaGroupId': 13,
  'categoryNaturalAreaId': 9,
  'name': 'Reserva Natural Para La Conservación De Los Ecosistemas Andinos',
  'departmentId': 15,
  'daneCode': 25,
  'landArea': 1.6955538082509,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 37,
  'areaGroupId': 13,
  'categoryNaturalAreaId': 9,
  'name': 'Reserva Natural Para La Conservación De Los Ecosistemas Andinos',
  'departmentId': 15,
  'daneCode': 25,
  'landArea': 1.6955538082509,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 38,
  'areaGroupId': 14,
  'categoryNaturalAreaId': 9,
  'name': 'Villa Paz',
  'departmentId': 15,
  'daneCode': 25,
  'landArea': 36.418430717288,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 39,
  'areaGroupId': 14,
  'categoryNaturalAreaId': 9,
  'name': 'Villa Paz',
  'departmentId': 15,
  'daneCode': 25,
  'landArea': 36.418430717288,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 40,
  'areaGroupId': 16,
  'categoryNaturalAreaId': 9,
  'name': 'La Gaviota',
  'departmentId': 8,
  'daneCode': 17,
  'landArea': 10.951307007013,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 41,
  'areaGroupId': 16,
  'categoryNaturalAreaId': 9,
  'name': 'La Gaviota',
  'departmentId': 8,
  'daneCode': 17,
  'landArea': 10.951307007013,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 42,
  'areaGroupId': 17,
  'categoryNaturalAreaId': 1,
  'name': 'Los Estoraques',
  'departmentId': 23,
  'daneCode': 54,
  'landArea': 1026.6821470615,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 43,
  'areaGroupId': 17,
  'categoryNaturalAreaId': 1,
  'name': 'Los Estoraques',
  'departmentId': 23,
  'daneCode': 54,
  'landArea': 26.762662263183,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 44,
  'areaGroupId': 17,
  'categoryNaturalAreaId': 1,
  'name': 'Los Estoraques',
  'departmentId': 23,
  'daneCode': 54,
  'landArea': 1053.4448093997,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 45,
  'areaGroupId': 18,
  'categoryNaturalAreaId': 9,
  'name': 'Buenos Aires',
  'departmentId': 31,
  'daneCode': 76,
  'landArea': 132.68820897734,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 46,
  'areaGroupId': 18,
  'categoryNaturalAreaId': 9,
  'name': 'Buenos Aires',
  'departmentId': 31,
  'daneCode': 76,
  'landArea': 132.68820897734,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 47,
  'areaGroupId': 19,
  'categoryNaturalAreaId': 9,
  'name': 'El Garcero',
  'departmentId': 6,
  'daneCode': 13,
  'landArea': 348.57607178558,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 48,
  'areaGroupId': 19,
  'categoryNaturalAreaId': 9,
  'name': 'El Garcero',
  'departmentId': 20,
  'daneCode': 47,
  'landArea': 25.895611862725,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 49,
  'areaGroupId': 19,
  'categoryNaturalAreaId': 9,
  'name': 'El Garcero',
  'departmentId': 6,
  'daneCode': 13,
  'landArea': 112.42761877055,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 50,
  'areaGroupId': 19,
  'categoryNaturalAreaId': 9,
  'name': 'El Garcero',
  'departmentId': 6,
  'daneCode': 13,
  'landArea': 236.1484535828,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 51,
  'areaGroupId': 19,
  'categoryNaturalAreaId': 9,
  'name': 'El Garcero',
  'departmentId': 20,
  'daneCode': 47,
  'landArea': 25.895611862725,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 52,
  'areaGroupId': 21,
  'categoryNaturalAreaId': 9,
  'name': 'El Guayabo',
  'departmentId': 8,
  'daneCode': 17,
  'landArea': 12.813213945054,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 53,
  'areaGroupId': 21,
  'categoryNaturalAreaId': 9,
  'name': 'El Guayabo',
  'departmentId': 8,
  'daneCode': 17,
  'landArea': 12.813213945054,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 54,
  'areaGroupId': 22,
  'categoryNaturalAreaId': 9,
  'name': 'Chicaque',
  'departmentId': 15,
  'daneCode': 25,
  'landArea': 292.24904839203,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 55,
  'areaGroupId': 22,
  'categoryNaturalAreaId': 9,
  'name': 'Chicaque',
  'departmentId': 15,
  'daneCode': 25,
  'landArea': 16.416333628004,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 56,
  'areaGroupId': 22,
  'categoryNaturalAreaId': 9,
  'name': 'Chicaque',
  'departmentId': 15,
  'daneCode': 25,
  'landArea': 275.83271501545,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 57,
  'areaGroupId': 23,
  'categoryNaturalAreaId': 9,
  'name': 'Pescador de Flores',
  'departmentId': 11,
  'daneCode': 19,
  'landArea': 1.2270611059571,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 58,
  'areaGroupId': 23,
  'categoryNaturalAreaId': 9,
  'name': 'Pescador de Flores',
  'departmentId': 11,
  'daneCode': 19,
  'landArea': 1.2270611059571,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 59,
  'areaGroupId': 24,
  'categoryNaturalAreaId': 7,
  'name': 'Alto Fragua - Indi Wasi',
  'departmentId': 18,
  'daneCode': 41,
  'landArea': 12.093546933764,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 60,
  'areaGroupId': 24,
  'categoryNaturalAreaId': 7,
  'name': 'Alto Fragua - Indi Wasi',
  'departmentId': 9,
  'daneCode': 18,
  'landArea': 17697.620409132,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 61,
  'areaGroupId': 24,
  'categoryNaturalAreaId': 7,
  'name': 'Alto Fragua - Indi Wasi',
  'departmentId': 11,
  'daneCode': 19,
  'landArea': 0.97240445181883,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 62,
  'areaGroupId': 24,
  'categoryNaturalAreaId': 7,
  'name': 'Alto Fragua - Indi Wasi',
  'departmentId': 9,
  'daneCode': 18,
  'landArea': 58383.481000018,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 63,
  'areaGroupId': 24,
  'categoryNaturalAreaId': 7,
  'name': 'Alto Fragua - Indi Wasi',
  'departmentId': 18,
  'daneCode': 41,
  'landArea': 12.093546933764,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 64,
  'areaGroupId': 24,
  'categoryNaturalAreaId': 7,
  'name': 'Alto Fragua - Indi Wasi',
  'departmentId': 11,
  'daneCode': 19,
  'landArea': 0.97240445181883,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 65,
  'areaGroupId': 24,
  'categoryNaturalAreaId': 7,
  'name': 'Alto Fragua - Indi Wasi',
  'departmentId': 9,
  'daneCode': 18,
  'landArea': 76081.101409158,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 66,
  'areaGroupId': 25,
  'categoryNaturalAreaId': 7,
  'name': 'Tayrona',
  'departmentId': None,
  'daneCode': 0,
  'landArea': None,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 67,
  'areaGroupId': 25,
  'categoryNaturalAreaId': 7,
  'name': 'Tayrona',
  'departmentId': 20,
  'daneCode': 47,
  'landArea': 12599.517227619,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 68,
  'areaGroupId': 25,
  'categoryNaturalAreaId': 7,
  'name': 'Tayrona',
  'departmentId': None,
  'daneCode': 0,
  'landArea': None,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 69,
  'areaGroupId': 25,
  'categoryNaturalAreaId': 7,
  'name': 'Tayrona',
  'departmentId': 20,
  'daneCode': 47,
  'landArea': 12599.517227619,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 70,
  'areaGroupId': 26,
  'categoryNaturalAreaId': 9,
  'name': 'El Refugio De Techotiva',
  'departmentId': 15,
  'daneCode': 25,
  'landArea': 4.5879408687136,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 71,
  'areaGroupId': 26,
  'categoryNaturalAreaId': 9,
  'name': 'El Refugio De Techotiva',
  'departmentId': 15,
  'daneCode': 25,
  'landArea': 4.5879408687136,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 72,
  'areaGroupId': 27,
  'categoryNaturalAreaId': 7,
  'name': 'Amacayacu',
  'departmentId': 1,
  'daneCode': 91,
  'landArea': 2.1584249212265,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 73,
  'areaGroupId': 27,
  'categoryNaturalAreaId': 7,
  'name': 'Amacayacu',
  'departmentId': 1,
  'daneCode': 91,
  'landArea': 259816.30186852,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 74,
  'areaGroupId': 27,
  'categoryNaturalAreaId': 7,
  'name': 'Amacayacu',
  'departmentId': 1,
  'daneCode': 91,
  'landArea': 7422.1428338633,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 75,
  'areaGroupId': 27,
  'categoryNaturalAreaId': 7,
  'name': 'Amacayacu',
  'departmentId': 1,
  'daneCode': 91,
  'landArea': 267240.60311543,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 76,
  'areaGroupId': 28,
  'categoryNaturalAreaId': 9,
  'name': 'Guayacanes Del Llano Verde',
  'departmentId': 22,
  'daneCode': 52,
  'landArea': 25.365536724853,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 77,
  'areaGroupId': 28,
  'categoryNaturalAreaId': 9,
  'name': 'Guayacanes Del Llano Verde',
  'departmentId': 22,
  'daneCode': 52,
  'landArea': 25.365536724853,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 78,
  'areaGroupId': 29,
  'categoryNaturalAreaId': 9,
  'name': 'El Trébol',
  'departmentId': 18,
  'daneCode': 41,
  'landArea': 39.993312710147,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 79,
  'areaGroupId': 29,
  'categoryNaturalAreaId': 9,
  'name': 'El Trébol',
  'departmentId': 18,
  'daneCode': 41,
  'landArea': 39.993312710147,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 80,
  'areaGroupId': 30,
  'categoryNaturalAreaId': 9,
  'name': 'Sanguare',
  'departmentId': 29,
  'daneCode': 70,
  'landArea': 864.10382702848,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 81,
  'areaGroupId': 30,
  'categoryNaturalAreaId': 9,
  'name': 'Sanguare',
  'departmentId': 29,
  'daneCode': 70,
  'landArea': 864.10382702848,
  'maritimeArea': None,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 82,
  'areaGroupId': 30,
  'categoryNaturalAreaId': 9,
  'name': 'Sanguare',
  'departmentId': None,
  'daneCode': 0,
  'landArea': None,
  'maritimeArea': 26.946561979545,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 83,
  'areaGroupId': 30,
  'categoryNaturalAreaId': 9,
  'name': 'Sanguare',
  'departmentId': None,
  'daneCode': 0,
  'landArea': None,
  'maritimeArea': 26.946561979545,
  'department': None,
  'categoryNaturalArea': None},
 {'id': 84,
  'areaGroupId': 31,
  'categoryNaturalAreaId': 7,
  'name': 'Uramba Bahía Málaga',
  'departmentId': None,
  'daneCode': 0,

In [14]:
import pandas as pd

df = pd.DataFrame(resp.json())

In [15]:
df

,id,areaGroupId,categoryNaturalAreaId,name,departmentId,daneCode,landArea,maritimeArea,department,categoryNaturalArea
0,1,6,7,Cueva de los Guácharos,18.0,41.0,4873.057594,NaN,None,None
1,2,6,7,Cueva de los Guácharos,18.0,41.0,15.759621,NaN,None,None
2,3,6,7,Cueva de los Guácharos,9.0,18.0,5.624746,NaN,None,None
3,4,6,7,Cueva de los Guácharos,11.0,19.0,1099.019145,NaN,None,None
4,5,6,7,Cueva de los Guácharos,9.0,18.0,1141.458976,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...
4342,4343,1924,3,La Corcova,31.0,76.0,46.215383,NaN,None,None
4343,4344,1924,3,La Corcova,31.0,76.0,46.570284,NaN,None,None
4344,4345,1925,6,Bosque Seco Alegrías y Páramo El Tibí y Mirafl...,31.0,76.0,14791.739872,NaN,None,None
4345,4346,1925,6,Bosque Seco Alegrías y Páramo El Tibí y Mirafl...,31.0,76.0,75.203067,NaN,None,None
4346,4347,1925,6,Bosque Seco Alegrías y Páramo El Tibí y Mirafl...,31.0,76.0,14866.942939,NaN,None,None

In [16]:
df.head(11)

,id,areaGroupId,categoryNaturalAreaId,name,departmentId,daneCode,landArea,maritimeArea,department,categoryNaturalArea
0,1,6,7,Cueva de los Guácharos,18.0,41.0,4873.057594,NaN,None,None
1,2,6,7,Cueva de los Guácharos,18.0,41.0,15.759621,NaN,None,None
2,3,6,7,Cueva de los Guácharos,9.0,18.0,5.624746,NaN,None,None
3,4,6,7,Cueva de los Guácharos,11.0,19.0,1099.019145,NaN,None,None
4,5,6,7,Cueva de los Guácharos,9.0,18.0,1141.458976,NaN,None,None
5,6,6,7,Cueva de los Guácharos,18.0,41.0,4888.817214,NaN,None,None
6,7,6,7,Cueva de los Guácharos,11.0,19.0,1099.019145,NaN,None,None
7,8,6,7,Cueva de los Guácharos,9.0,18.0,1147.083722,NaN,None,None
8,9,8,2,Nukak,17.0,95.0,4714.539767,NaN,None,None
9,10,8,2,Nukak,17.0,95.0,645756.283595,NaN,None,None
10,11,8,2,Nukak,32.0,97.0,141.761056,NaN,None,None

In [17]:
df.tail(11)

,id,areaGroupId,categoryNaturalAreaId,name,departmentId,daneCode,landArea,maritimeArea,department,categoryNaturalArea
4336,4337,1921,9,Cañón De Los Guácharos,11.0,19.0,6.575005,NaN,None,None
4337,4338,1922,9,La Indomable,33.0,99.0,745.470904,NaN,None,None
4338,4339,1922,9,La Indomable,33.0,99.0,745.470904,NaN,None,None
4339,4340,1923,9,Los Laureles,30.0,73.0,34.716103,NaN,None,None
4340,4341,1923,9,Los Laureles,30.0,73.0,34.716103,NaN,None,None
4341,4342,1924,3,La Corcova,31.0,76.0,0.354901,NaN,None,None
4342,4343,1924,3,La Corcova,31.0,76.0,46.215383,NaN,None,None
4343,4344,1924,3,La Corcova,31.0,76.0,46.570284,NaN,None,None
4344,4345,1925,6,Bosque Seco Alegrías y Páramo El Tibí y Mirafl...,31.0,76.0,14791.739872,NaN,None,None
4345,4346,1925,6,Bosque Seco Alegrías y Páramo El Tibí y Mirafl...,31.0,76.0,75.203067,NaN,None,None
4346,4347,1925,6,Bosque Seco Alegrías y Páramo El Tibí y Mirafl...,31.0,76.0,14866.942939,NaN,None,None

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4347 entries, 0 to 4346
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     4347 non-null   int64
 1   areaGroupId            4347 non-null   int64
 2   categoryNaturalAreaId  4347 non-null   int64
 3   name                   4347 non-null   str
 4   departmentId           4246 non-null   float64
 5   daneCode               4330 non-null   float64
 6   landArea               4263 non-null   float64
 7   maritimeArea           76 non-null     float64
 8   department             0 non-null      object
 9   categoryNaturalArea    0 non-null      object
dtypes: float64(4), int64(3), object(2), str(1)
memory usage: 339.7+ KB

In [19]:
df.shape

(4347, 10)

In [21]:
df.isnull().sum()

id                          0
areaGroupId                 0
categoryNaturalAreaId       0
name                        0
departmentId              101
daneCode                   17
landArea                   84
maritimeArea             4271
department               4347
categoryNaturalArea      4347
dtype: int64

In [22]:
df = df.drop(['department'], axis=1)

df = df.drop(['categoryNaturalArea'], axis=1)

In [23]:
df['landArea'] = df['landArea'].fillna('No Asignado')

df['daneCode'] = df['daneCode'].fillna(0)

df['departmentId'] = df['departmentId'].fillna(0)

In [24]:
df['maritimeArea'] = df['maritimeArea'].fillna(0)

In [25]:
df.isnull().sum()

id                       0
areaGroupId              0
categoryNaturalAreaId    0
name                     0
departmentId             0
daneCode                 0
landArea                 0
maritimeArea             0
dtype: int64

In [29]:
df['landArea']= pd.to_numeric(df['landArea'], errors='coerce')

df.sort_values(by='landArea', ascending=False).head(5)

,id,areaGroupId,categoryNaturalAreaId,name,departmentId,daneCode,landArea,maritimeArea,Hectareas_Terrestres
179,180,57,7,La Serranía de Chiribiquete,9.00,18.00,3203280.77,0.00,320.33
173,174,57,7,La Serranía de Chiribiquete,9.00,18.00,2216284.51,0.00,221.63
164,165,55,2,Puinawai,16.00,94.00,1096353.77,0.00,109.64
178,179,57,7,La Serranía de Chiribiquete,17.00,95.00,1063018.60,0.00,106.30
490,490,146,7,Río Puré,1.00,91.00,970643.43,0.00,97.06

In [27]:
df['landArea'] = pd.to_numeric(df['landArea'], errors='coerce').fillna(0)
pd.set_option('display.float_format', lambda x: '%.2f' % x)
df['Hectareas_Terrestres'] = df['landArea'] / 10000

In [32]:
df

,id,areaGroupId,categoryNaturalAreaId,name,departmentId,daneCode,landArea,maritimeArea,Hectareas_Terrestres
0,1,6,7,Cueva de los Guácharos,18.00,41.00,4873.06,0.00,0.49
1,2,6,7,Cueva de los Guácharos,18.00,41.00,15.76,0.00,0.00
2,3,6,7,Cueva de los Guácharos,9.00,18.00,5.62,0.00,0.00
3,4,6,7,Cueva de los Guácharos,11.00,19.00,1099.02,0.00,0.11
4,5,6,7,Cueva de los Guácharos,9.00,18.00,1141.46,0.00,0.11
...,...,...,...,...,...,...,...,...,...
4342,4343,1924,3,La Corcova,31.00,76.00,46.22,0.00,0.00
4343,4344,1924,3,La Corcova,31.00,76.00,46.57,0.00,0.00
4344,4345,1925,6,Bosque Seco Alegrías y Páramo El Tibí y Mirafl...,31.00,76.00,14791.74,0.00,1.48
4345,4346,1925,6,Bosque Seco Alegrías y Páramo El Tibí y Mirafl...,31.00,76.00,75.20,0.00,0.01
4346,4347,1925,6,Bosque Seco Alegrías y Páramo El Tibí y Mirafl...,31.00,76.00,14866.94,0.00,1.49

In [34]:
import pandas as pd


df.to_csv('archivo_final.csv', index=False)